export enum AuditEntity {
  Cart = 'cart',
  Program = 'program',
  ProgramTemplate = 'programTemplate',
  Sport = 'sport',
  Team = 'team',
  Season = 'season',
  Person = 'person',
  Family = 'family',
  File = 'file',
  SeasonProgram = 'seasonProgram',
  TeamAssignment = 'teamAssignment',
  PaymentPlan = 'paymentPlan',
  PaymentMethod = 'paymentMethod',
  Other = 'other',
  User = 'user',
}
